node {

        stage('Build') {
            			
            	
  				sh "cd ${workspace}/simple-java-maven-app/; ${mvnHome}/bin/mvn install -Pdevelopment"
            	sh 'mvn -B -DskipTests clean package'            
        }
        
    
}
